# SPDX-FileCopyrightText: 2020 Christopher Kerr
# SPDX-License-Identifier: GPL-3.0-or-later
sudo: false
language: python
cache:
  directories:
    - .tox
    - .pytest_cache
    - tests/testdata
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install tox-travis
  - sh get_testdata.sh
script: tox
